// Code generated by internal/gen from openapi.json (Dimail API v0.8.2); DO NOT EDIT.

package dimail

import (
	"context"
	"encoding/json"
	"net/url"
	"strconv"
)

// GetPublicAliases issues GET /aliases: Get Aliases.
func (c *Client) GetPublicAliases(ctx context.Context, destination *string) ([]PubAlias, error) {
	q := url.Values{}
	if destination != nil {
		q.Set("destination", *destination)
	}
	return doList[PubAlias](c, ctx, "GET", "/aliases", q, nil)
}

// PostPublicAlias issues POST /aliases: Post Alias.
func (c *Client) PostPublicAlias(ctx context.Context, body *CreatePubAlias) (*PubAlias, error) {
	return doJSON[PubAlias](c, ctx, "POST", "/aliases", nil, body)
}

// GetPublicAliasDomains issues GET /aliases/domains: Get Domains.
func (c *Client) GetPublicAliasDomains(ctx context.Context, destination *string) ([]string, error) {
	q := url.Values{}
	if destination != nil {
		q.Set("destination", *destination)
	}
	return doList[string](c, ctx, "GET", "/aliases/domains", q, nil)
}

// PatchPublicAlias issues PATCH /aliases/{user_name}@{domain_name}/{destination}: Patch Alias.
func (c *Client) PatchPublicAlias(ctx context.Context, userName string, domainName string, destination string, body *UpdatePubAlias) (*PubAlias, error) {
	return doJSON[PubAlias](c, ctx, "PATCH", "/aliases/"+esc(userName)+"@"+esc(domainName)+"/"+esc(destination), nil, body)
}

// DeletePublicAlias issues DELETE /aliases/{user_name}@{domain_name}/{destination}: Delete Alias.
func (c *Client) DeletePublicAlias(ctx context.Context, userName string, domainName string, destination string) error {
	return doVoid(c, ctx, "DELETE", "/aliases/"+esc(userName)+"@"+esc(domainName)+"/"+esc(destination), nil, nil)
}

// GetAllow issues GET /allows/: Get Allows.
func (c *Client) GetAllow(ctx context.Context, username *string, domain *string) ([]Allowed, error) {
	q := url.Values{}
	if username != nil {
		q.Set("username", *username)
	}
	if domain != nil {
		q.Set("domain", *domain)
	}
	return doList[Allowed](c, ctx, "GET", "/allows/", q, nil)
}

// PostAllow issues POST /allows/: Post Allow.
func (c *Client) PostAllow(ctx context.Context, body *Allowed) (*Allowed, error) {
	return doJSON[Allowed](c, ctx, "POST", "/allows/", nil, body)
}

// DeleteAllow issues DELETE /allows/{domain_name}/{user_name}: Delete Allow.
func (c *Client) DeleteAllow(ctx context.Context, domainName string, userName string) error {
	return doVoid(c, ctx, "DELETE", "/allows/"+esc(domainName)+"/"+esc(userName), nil, nil)
}

// GetCode issues GET /code/{code_string}: Get Code.
func (c *Client) GetCode(ctx context.Context, codeString string) (*MailboxCode, error) {
	return doJSON[MailboxCode](c, ctx, "GET", "/code/"+esc(codeString), nil, nil)
}

// GetDomains issues GET /domains/: Get all domains.
func (c *Client) GetDomains(ctx context.Context) ([]Domain, error) {
	return doList[Domain](c, ctx, "GET", "/domains/", nil, nil)
}

// PostDomain issues POST /domains/: Create a domain.
func (c *Client) PostDomain(ctx context.Context, noCheck *string, body *CreateDomain) (*Domain, error) {
	q := url.Values{}
	if noCheck != nil {
		q.Set("no_check", *noCheck)
	}
	return doJSON[Domain](c, ctx, "POST", "/domains/", q, body)
}

// GetDomain issues GET /domains/{domain_name}: Get a domain.
func (c *Client) GetDomain(ctx context.Context, domainName string) (*Domain, error) {
	return doJSON[Domain](c, ctx, "GET", "/domains/"+esc(domainName), nil, nil)
}

// PatchDomain issues PATCH /domains/{domain_name}: Update a domain.
func (c *Client) PatchDomain(ctx context.Context, domainName string, body *UpdateDomain) (*Domain, error) {
	return doJSON[Domain](c, ctx, "PATCH", "/domains/"+esc(domainName), nil, body)
}

// DeleteDomain issues DELETE /domains/{domain_name}: Delete a domain.
func (c *Client) DeleteDomain(ctx context.Context, domainName string) error {
	return doVoid(c, ctx, "DELETE", "/domains/"+esc(domainName), nil, nil)
}

// GetAddress issues GET /domains/{domain_name}/address/{user_name}: Get Address.
func (c *Client) GetAddress(ctx context.Context, domainName string, userName string) (*Address, error) {
	return doJSON[Address](c, ctx, "GET", "/domains/"+esc(domainName)+"/address/"+esc(userName), nil, nil)
}

// GetAlias issues GET /domains/{domain_name}/aliases/: Get Alias.
func (c *Client) GetAlias(ctx context.Context, domainName string, userName *string, destination *string) ([]Alias, error) {
	q := url.Values{}
	if userName != nil {
		q.Set("user_name", *userName)
	}
	if destination != nil {
		q.Set("destination", *destination)
	}
	return doList[Alias](c, ctx, "GET", "/domains/"+esc(domainName)+"/aliases/", q, nil)
}

// PostAliasDomainsDomainNameAliasesPost issues POST /domains/{domain_name}/aliases/: Post Alias.
func (c *Client) PostAliasDomainsDomainNameAliasesPost(ctx context.Context, domainName string, body *CreateAlias) (*Alias, error) {
	return doJSON[Alias](c, ctx, "POST", "/domains/"+esc(domainName)+"/aliases/", nil, body)
}

// PatchAlias issues PATCH /domains/{domain_name}/aliases/{user_name}/{destination}: Patch Alias.
func (c *Client) PatchAlias(ctx context.Context, domainName string, userName string, destination string, body *UpdateAlias) (*Alias, error) {
	return doJSON[Alias](c, ctx, "PATCH", "/domains/"+esc(domainName)+"/aliases/"+esc(userName)+"/"+esc(destination), nil, body)
}

// DeleteAlias issues DELETE /domains/{domain_name}/aliases/{user_name}/{destination}: Delete Alias.
func (c *Client) DeleteAlias(ctx context.Context, domainName string, userName string, destination string) error {
	return doVoid(c, ctx, "DELETE", "/domains/"+esc(domainName)+"/aliases/"+esc(userName)+"/"+esc(destination), nil, nil)
}

// CheckDomain issues GET /domains/{domain_name}/check: Check Domain.
func (c *Client) CheckDomain(ctx context.Context, domainName string) (*Domain, error) {
	return doJSON[Domain](c, ctx, "GET", "/domains/"+esc(domainName)+"/check", nil, nil)
}

// FixDomain issues GET /domains/{domain_name}/fix: Fix Domain.
func (c *Client) FixDomain(ctx context.Context, domainName string) (*Domain, error) {
	return doJSON[Domain](c, ctx, "GET", "/domains/"+esc(domainName)+"/fix", nil, nil)
}

// GetForwards issues GET /domains/{domain_name}/forwards/: Get Forwards.
func (c *Client) GetForwards(ctx context.Context, domainName string) ([]Forward, error) {
	return doList[Forward](c, ctx, "GET", "/domains/"+esc(domainName)+"/forwards/", nil, nil)
}

// GetForward issues GET /domains/{domain_name}/forwards/{user_name}: Get Forward.
func (c *Client) GetForward(ctx context.Context, domainName string, userName string) (*Forward, error) {
	return doJSON[Forward](c, ctx, "GET", "/domains/"+esc(domainName)+"/forwards/"+esc(userName), nil, nil)
}

// PostForward issues POST /domains/{domain_name}/forwards/{user_name}: Post Forward.
func (c *Client) PostForward(ctx context.Context, domainName string, userName string, body *CreateForward) (*Forward, error) {
	return doJSON[Forward](c, ctx, "POST", "/domains/"+esc(domainName)+"/forwards/"+esc(userName), nil, body)
}

// PatchForward issues PATCH /domains/{domain_name}/forwards/{user_name}: Patch Forward.
func (c *Client) PatchForward(ctx context.Context, domainName string, userName string, body *UpdateForward) (*Forward, error) {
	return doJSON[Forward](c, ctx, "PATCH", "/domains/"+esc(domainName)+"/forwards/"+esc(userName), nil, body)
}

// DeleteForward issues DELETE /domains/{domain_name}/forwards/{user_name}: Delete Forward.
func (c *Client) DeleteForward(ctx context.Context, domainName string, userName string) error {
	return doVoid(c, ctx, "DELETE", "/domains/"+esc(domainName)+"/forwards/"+esc(userName), nil, nil)
}

// GetMailboxes issues GET /domains/{domain_name}/mailboxes/: Get Mailboxes.
func (c *Client) GetMailboxes(ctx context.Context, domainName string) ([]Mailbox, error) {
	return doList[Mailbox](c, ctx, "GET", "/domains/"+esc(domainName)+"/mailboxes/", nil, nil)
}

// GetMailbox issues GET /domains/{domain_name}/mailboxes/{user_name}: Get Mailbox.
func (c *Client) GetMailbox(ctx context.Context, domainName string, userName string) (*Mailbox, error) {
	return doJSON[Mailbox](c, ctx, "GET", "/domains/"+esc(domainName)+"/mailboxes/"+esc(userName), nil, nil)
}

// PostMailbox issues POST /domains/{domain_name}/mailboxes/{user_name}: Post Mailbox.
func (c *Client) PostMailbox(ctx context.Context, domainName string, userName string, body *CreateMailbox) (*NewMailbox, error) {
	return doJSON[NewMailbox](c, ctx, "POST", "/domains/"+esc(domainName)+"/mailboxes/"+esc(userName), nil, body)
}

// PatchMailbox issues PATCH /domains/{domain_name}/mailboxes/{user_name}: Patch Mailbox.
func (c *Client) PatchMailbox(ctx context.Context, domainName string, userName string, body *UpdateMailbox) (*Mailbox, error) {
	return doJSON[Mailbox](c, ctx, "PATCH", "/domains/"+esc(domainName)+"/mailboxes/"+esc(userName), nil, body)
}

// DeleteMailbox issues DELETE /domains/{domain_name}/mailboxes/{user_name}: Delete Mailbox.
func (c *Client) DeleteMailbox(ctx context.Context, domainName string, userName string) error {
	return doVoid(c, ctx, "DELETE", "/domains/"+esc(domainName)+"/mailboxes/"+esc(userName), nil, nil)
}

// GetAppPasswords issues GET /domains/{domain_name}/mailboxes/{user_name}/app_passwords: Get App Passwords.
func (c *Client) GetAppPasswords(ctx context.Context, domainName string, userName string) ([]AppPassword, error) {
	return doList[AppPassword](c, ctx, "GET", "/domains/"+esc(domainName)+"/mailboxes/"+esc(userName)+"/app_passwords", nil, nil)
}

// PostAppPassword issues POST /domains/{domain_name}/mailboxes/{user_name}/app_passwords: Post App Password.
func (c *Client) PostAppPassword(ctx context.Context, domainName string, userName string, body *CreateAppPassword) (*NewAppPassword, error) {
	return doJSON[NewAppPassword](c, ctx, "POST", "/domains/"+esc(domainName)+"/mailboxes/"+esc(userName)+"/app_passwords", nil, body)
}

// GetAppPassword issues GET /domains/{domain_name}/mailboxes/{user_name}/app_passwords/{uuid}: Get App Password.
func (c *Client) GetAppPassword(ctx context.Context, domainName string, userName string, uuid string) (*AppPassword, error) {
	return doJSON[AppPassword](c, ctx, "GET", "/domains/"+esc(domainName)+"/mailboxes/"+esc(userName)+"/app_passwords/"+esc(uuid), nil, nil)
}

// DeleteAppPassword issues DELETE /domains/{domain_name}/mailboxes/{user_name}/app_passwords/{uuid}: Delete App Password.
func (c *Client) DeleteAppPassword(ctx context.Context, domainName string, userName string, uuid string) error {
	return doVoid(c, ctx, "DELETE", "/domains/"+esc(domainName)+"/mailboxes/"+esc(userName)+"/app_passwords/"+esc(uuid), nil, nil)
}

// CheckPassword issues POST /domains/{domain_name}/mailboxes/{user_name}/check_password: Check Password.
func (c *Client) CheckPassword(ctx context.Context, domainName string, userName string, body *MailboxPassword) (bool, error) {
	return doValue[bool](c, ctx, "POST", "/domains/"+esc(domainName)+"/mailboxes/"+esc(userName)+"/check_password", nil, body)
}

// PostMailboxCode issues POST /domains/{domain_name}/mailboxes/{user_name}/code: Post Mailbox Code.
func (c *Client) PostMailboxCode(ctx context.Context, domainName string, userName string, body *CreateMailboxCode) (*MailboxCode, error) {
	return doJSON[MailboxCode](c, ctx, "POST", "/domains/"+esc(domainName)+"/mailboxes/"+esc(userName)+"/code", nil, body)
}

// ForcePassword issues POST /domains/{domain_name}/mailboxes/{user_name}/force_password: Force the password of a mailbox.
func (c *Client) ForcePassword(ctx context.Context, domainName string, userName string, body *MailboxForcePassword) (*NewMailbox, error) {
	return doJSON[NewMailbox](c, ctx, "POST", "/domains/"+esc(domainName)+"/mailboxes/"+esc(userName)+"/force_password", nil, body)
}

// GetMailboxIdentities issues GET /domains/{domain_name}/mailboxes/{user_name}/identities: Get Identities.
func (c *Client) GetMailboxIdentities(ctx context.Context, domainName string, userName string) ([]string, error) {
	return doList[string](c, ctx, "GET", "/domains/"+esc(domainName)+"/mailboxes/"+esc(userName)+"/identities", nil, nil)
}

// PostMailboxIdentity issues POST /domains/{domain_name}/mailboxes/{user_name}/identities/{identity}: Post Identities.
func (c *Client) PostMailboxIdentity(ctx context.Context, domainName string, userName string, identity string) (*json.RawMessage, error) {
	return doJSON[json.RawMessage](c, ctx, "POST", "/domains/"+esc(domainName)+"/mailboxes/"+esc(userName)+"/identities/"+esc(identity), nil, nil)
}

// GetMasters issues GET /domains/{domain_name}/mailboxes/{user_name}/master_of: Get Masters.
func (c *Client) GetMasters(ctx context.Context, domainName string, userName string) ([]Secondary, error) {
	return doList[Secondary](c, ctx, "GET", "/domains/"+esc(domainName)+"/mailboxes/"+esc(userName)+"/master_of", nil, nil)
}

// GetMaster issues GET /domains/{domain_name}/mailboxes/{user_name}/master_of/{secondary_email}: Get Master.
func (c *Client) GetMaster(ctx context.Context, domainName string, userName string, secondaryEmail string) (*Secondary, error) {
	return doJSON[Secondary](c, ctx, "GET", "/domains/"+esc(domainName)+"/mailboxes/"+esc(userName)+"/master_of/"+esc(secondaryEmail), nil, nil)
}

// PostMaster issues POST /domains/{domain_name}/mailboxes/{user_name}/master_of/{secondary_email}: Post Master.
func (c *Client) PostMaster(ctx context.Context, domainName string, userName string, secondaryEmail string, body *CreateSecondary) (*Secondary, error) {
	return doJSON[Secondary](c, ctx, "POST", "/domains/"+esc(domainName)+"/mailboxes/"+esc(userName)+"/master_of/"+esc(secondaryEmail), nil, body)
}

// DeleteMaster issues DELETE /domains/{domain_name}/mailboxes/{user_name}/master_of/{secondary_email}: Delete Master.
func (c *Client) DeleteMaster(ctx context.Context, domainName string, userName string, secondaryEmail string) error {
	return doVoid(c, ctx, "DELETE", "/domains/"+esc(domainName)+"/mailboxes/"+esc(userName)+"/master_of/"+esc(secondaryEmail), nil, nil)
}

// GetMastereds issues GET /domains/{domain_name}/mailboxes/{user_name}/mastered_by: Get Mastereds.
func (c *Client) GetMastereds(ctx context.Context, domainName string, userName string) ([]Secondary, error) {
	return doList[Secondary](c, ctx, "GET", "/domains/"+esc(domainName)+"/mailboxes/"+esc(userName)+"/mastered_by", nil, nil)
}

// ResetPassword issues POST /domains/{domain_name}/mailboxes/{user_name}/reset_password: Reset Password.
func (c *Client) ResetPassword(ctx context.Context, domainName string, userName string) (*NewMailbox, error) {
	return doJSON[NewMailbox](c, ctx, "POST", "/domains/"+esc(domainName)+"/mailboxes/"+esc(userName)+"/reset_password", nil, nil)
}

// GetDomainSpecs issues GET /domains/{domain_name}/spec: Spec Domain.
func (c *Client) GetDomainSpecs(ctx context.Context, domainName string) ([]DomainSpec, error) {
	return doList[DomainSpec](c, ctx, "GET", "/domains/"+esc(domainName)+"/spec", nil, nil)
}

// GetIdentities issues GET /identities: Get Identities.
func (c *Client) GetIdentities(ctx context.Context, identity *string) ([]string, error) {
	q := url.Values{}
	if identity != nil {
		q.Set("identity", *identity)
	}
	return doList[string](c, ctx, "GET", "/identities", q, nil)
}

// PostIdentity issues POST /identities: Post Identities.
func (c *Client) PostIdentity(ctx context.Context, body *CreateIdentity) (*json.RawMessage, error) {
	return doJSON[json.RawMessage](c, ctx, "POST", "/identities", nil, body)
}

// DeleteIdentities issues DELETE /identities/{proconnect}/{email}: Delete Identities.
func (c *Client) DeleteIdentities(ctx context.Context, proconnect string, email string) error {
	return doVoid(c, ctx, "DELETE", "/identities/"+esc(proconnect)+"/"+esc(email), nil, nil)
}

// GetServerLogs issues GET /logs/: Get Logs.
func (c *Client) GetServerLogs(ctx context.Context) (*ServerLogs, error) {
	return doJSON[ServerLogs](c, ctx, "GET", "/logs/", nil, nil)
}

// GetCrashLogs issues GET /logs/crashes: Get Crashes.
func (c *Client) GetCrashLogs(ctx context.Context) ([]CrashInfo, error) {
	return doList[CrashInfo](c, ctx, "GET", "/logs/crashes", nil, nil)
}

// GetCrashLog issues GET /logs/crashes/{crash_name}: Get Crash.
func (c *Client) GetCrashLog(ctx context.Context, crashName string) (*ServerLogs, error) {
	return doJSON[ServerLogs](c, ctx, "GET", "/logs/crashes/"+esc(crashName), nil, nil)
}

// DeleteCrashLog issues DELETE /logs/crashes/{crash_name}: Del Crash.
func (c *Client) DeleteCrashLog(ctx context.Context, crashName string) error {
	return doVoid(c, ctx, "DELETE", "/logs/crashes/"+esc(crashName), nil, nil)
}

// GetMyAliases issues GET /my/aliases: Get My Aliases.
func (c *Client) GetMyAliases(ctx context.Context) ([]string, error) {
	return doList[string](c, ctx, "GET", "/my/aliases", nil, nil)
}

// GetMyDomains issues GET /my/domains: Get My Domains.
func (c *Client) GetMyDomains(ctx context.Context) ([]string, error) {
	return doList[string](c, ctx, "GET", "/my/domains", nil, nil)
}

// GetMyMailboxes issues GET /my/mailboxes: Get My Mailboxes.
func (c *Client) GetMyMailboxes(ctx context.Context) ([]string, error) {
	return doList[string](c, ctx, "GET", "/my/mailboxes", nil, nil)
}

// GetMyResources issues GET /my/resources: Get My Resources.
func (c *Client) GetMyResources(ctx context.Context) (*VisibleResources, error) {
	return doJSON[VisibleResources](c, ctx, "GET", "/my/resources", nil, nil)
}

// UnauthGetDomain issues GET /public/domains/{domain_name}: Checks if a domain is managed by our platform.
func (c *Client) UnauthGetDomain(ctx context.Context, domainName string) (*json.RawMessage, error) {
	return doJSON[json.RawMessage](c, ctx, "GET", "/public/domains/"+esc(domainName), nil, nil)
}

// InternalCheckContexts issues POST /system/check_contexts: Check Contexts.
func (c *Client) InternalCheckContexts(ctx context.Context, body *CheckContexts) (*CheckedContexts, error) {
	return doJSON[CheckedContexts](c, ctx, "POST", "/system/check_contexts", nil, body)
}

// InternalPatchDatabase issues PATCH /system/database/{db_name}: Patch Database.
func (c *Client) InternalPatchDatabase(ctx context.Context, dbName string, body *UpdateDatabase) (*json.RawMessage, error) {
	return doJSON[json.RawMessage](c, ctx, "PATCH", "/system/database/"+esc(dbName), nil, body)
}

// InternalPostDatabase issues POST /system/database/{db_name}/{schema_name}: Post Database.
func (c *Client) InternalPostDatabase(ctx context.Context, dbName string, schemaName string) (*SchemaName, error) {
	return doJSON[SchemaName](c, ctx, "POST", "/system/database/"+esc(dbName)+"/"+esc(schemaName), nil, nil)
}

// InternalDisconnectUser issues GET /system/disconnect/{domain_name}/{user_name}: Get Disconnect.
func (c *Client) InternalDisconnectUser(ctx context.Context, domainName string, userName string) (*json.RawMessage, error) {
	return doJSON[json.RawMessage](c, ctx, "GET", "/system/disconnect/"+esc(domainName)+"/"+esc(userName), nil, nil)
}

// HealthCheck issues GET /system/health_check: Get Health Check.
func (c *Client) HealthCheck(ctx context.Context) (*ServerStatus, error) {
	return doJSON[ServerStatus](c, ctx, "GET", "/system/health_check", nil, nil)
}

// InternalImportDomain issues PATCH /system/import_domain/{domain_name}: Import Domain.
func (c *Client) InternalImportDomain(ctx context.Context, domainName string, body *ImportDomain) (*json.RawMessage, error) {
	return doJSON[json.RawMessage](c, ctx, "PATCH", "/system/import_domain/"+esc(domainName), nil, body)
}

// InternalMailboxInfo issues GET /system/mailbox_info/{domain_name}/{user_name}: Get Mailbox Info.
func (c *Client) InternalMailboxInfo(ctx context.Context, domainName string, userName string) (*MailboxInfo, error) {
	return doJSON[MailboxInfo](c, ctx, "GET", "/system/mailbox_info/"+esc(domainName)+"/"+esc(userName), nil, nil)
}

// InternalMailboxesInfo issues GET /system/mailboxes_info/{domain_name}: Get Mailboxes Info.
func (c *Client) InternalMailboxesInfo(ctx context.Context, domainName string) ([]MailboxInfo, error) {
	return doList[MailboxInfo](c, ctx, "GET", "/system/mailboxes_info/"+esc(domainName), nil, nil)
}

// InternalGetMailqueue issues GET /system/mailqueue/{domain_name}/{user_name}: Get Mailqueue.
func (c *Client) InternalGetMailqueue(ctx context.Context, domainName string, userName string) ([]string, error) {
	return doList[string](c, ctx, "GET", "/system/mailqueue/"+esc(domainName)+"/"+esc(userName), nil, nil)
}

// InternalMoveMailbox issues GET /system/move_mailbox/{domain_name}/{user_name}: Get Move Mailbox.
func (c *Client) InternalMoveMailbox(ctx context.Context, domainName string, userName string) (*json.RawMessage, error) {
	return doJSON[json.RawMessage](c, ctx, "GET", "/system/move_mailbox/"+esc(domainName)+"/"+esc(userName), nil, nil)
}

// GetRateLimits issues GET /system/rate_limits: Get Rate Limits.
func (c *Client) GetRateLimits(ctx context.Context) ([]RateLimit, error) {
	return doList[RateLimit](c, ctx, "GET", "/system/rate_limits", nil, nil)
}

// GetRateLimit issues GET /system/rate_limits/{name}: Get Rate Limit.
func (c *Client) GetRateLimit(ctx context.Context, name string) (*RateLimit, error) {
	return doJSON[RateLimit](c, ctx, "GET", "/system/rate_limits/"+esc(name), nil, nil)
}

// PostRateLimit issues POST /system/rate_limits/{name}: Post Rate Limit.
func (c *Client) PostRateLimit(ctx context.Context, name string, body *RateLimit) (*RateLimit, error) {
	return doJSON[RateLimit](c, ctx, "POST", "/system/rate_limits/"+esc(name), nil, body)
}

// PatchRateLimit issues PATCH /system/rate_limits/{name}: Patch Rate Limit.
func (c *Client) PatchRateLimit(ctx context.Context, name string, body *RateLimit) (*RateLimit, error) {
	return doJSON[RateLimit](c, ctx, "PATCH", "/system/rate_limits/"+esc(name), nil, body)
}

// DeleteRateLimit issues DELETE /system/rate_limits/{name}: Delete Rate Limit.
func (c *Client) DeleteRateLimit(ctx context.Context, name string) error {
	return doVoid(c, ctx, "DELETE", "/system/rate_limits/"+esc(name), nil, nil)
}

// InternalShutdown issues GET /system/shutdown: Get Shutdown.
func (c *Client) InternalShutdown(ctx context.Context) (*json.RawMessage, error) {
	return doJSON[json.RawMessage](c, ctx, "GET", "/system/shutdown", nil, nil)
}

// InternalGetStoreInfo issues GET /system/store_info/{store_name}: Get Store Info.
func (c *Client) InternalGetStoreInfo(ctx context.Context, storeName string) (*StoreInfo, error) {
	return doJSON[StoreInfo](c, ctx, "GET", "/system/store_info/"+esc(storeName), nil, nil)
}

// InternalGetStoresInfo issues GET /system/stores_info: Get Stores Info.
func (c *Client) InternalGetStoresInfo(ctx context.Context) ([]StoreInfo, error) {
	return doList[StoreInfo](c, ctx, "GET", "/system/stores_info", nil, nil)
}

// GetTechDomain issues GET /system/tech_domain: Get Tech Domain.
func (c *Client) GetTechDomain(ctx context.Context) (*TechDomain, error) {
	return doJSON[TechDomain](c, ctx, "GET", "/system/tech_domain", nil, nil)
}

// GetVersion issues GET /system/version: Get Version.
func (c *Client) GetVersion(ctx context.Context) (*ApiVersion, error) {
	return doJSON[ApiVersion](c, ctx, "GET", "/system/version", nil, nil)
}

// GetToken issues GET /token/: Get a token for a user.
func (c *Client) GetToken(ctx context.Context, username *string) (*Token, error) {
	q := url.Values{}
	if username != nil {
		q.Set("username", *username)
	}
	return doJSON[Token](c, ctx, "GET", "/token/", q, nil)
}

// GetUsers issues GET /users/: Get Users.
func (c *Client) GetUsers(ctx context.Context) ([]User, error) {
	return doList[User](c, ctx, "GET", "/users/", nil, nil)
}

// PostUser issues POST /users/: Post User.
func (c *Client) PostUser(ctx context.Context, body *CreateUser) (*User, error) {
	return doJSON[User](c, ctx, "POST", "/users/", nil, body)
}

// GetUserByProconnectIdentity issues GET /users/identity/{proconnect}: Get User By Identity.
func (c *Client) GetUserByProconnectIdentity(ctx context.Context, proconnect string) (*User, error) {
	return doJSON[User](c, ctx, "GET", "/users/identity/"+esc(proconnect), nil, nil)
}

// GetUser issues GET /users/{user_name}: Get User.
func (c *Client) GetUser(ctx context.Context, userName string) (*User, error) {
	return doJSON[User](c, ctx, "GET", "/users/"+esc(userName), nil, nil)
}

// DeleteUser issues DELETE /users/{user_name}: Delete User.
func (c *Client) DeleteUser(ctx context.Context, userName string) error {
	return doVoid(c, ctx, "DELETE", "/users/"+esc(userName), nil, nil)
}

// PatchUser issues PATCH /users/{user}: Patch User.
func (c *Client) PatchUser(ctx context.Context, user string, body *UpdateUser) (*User, error) {
	return doJSON[User](c, ctx, "PATCH", "/users/"+esc(user), nil, body)
}

// GetMailboxesV2 issues GET /v2/domains/{domain_name}/mailboxes/: Get Mailboxes V2.
func (c *Client) GetMailboxesV2(ctx context.Context, domainName string, withExtras *bool) ([]Mailbox2, error) {
	q := url.Values{}
	if withExtras != nil {
		q.Set("with_extras", strconv.FormatBool(*withExtras))
	}
	return doList[Mailbox2](c, ctx, "GET", "/v2/domains/"+esc(domainName)+"/mailboxes/", q, nil)
}

// GetMailboxV2 issues GET /v2/domains/{domain_name}/mailboxes/{user_name}: Get Mailbox V2.
func (c *Client) GetMailboxV2(ctx context.Context, domainName string, userName string, withExtras *bool) (*Mailbox2, error) {
	q := url.Values{}
	if withExtras != nil {
		q.Set("with_extras", strconv.FormatBool(*withExtras))
	}
	return doJSON[Mailbox2](c, ctx, "GET", "/v2/domains/"+esc(domainName)+"/mailboxes/"+esc(userName), q, nil)
}

// PostMailboxV2 issues POST /v2/domains/{domain_name}/mailboxes/{user_name}: Post Mailbox V2.
func (c *Client) PostMailboxV2(ctx context.Context, domainName string, userName string, body *CreateMailbox2) (*NewMailbox, error) {
	return doJSON[NewMailbox](c, ctx, "POST", "/v2/domains/"+esc(domainName)+"/mailboxes/"+esc(userName), nil, body)
}

// PatchMailboxV2 issues PATCH /v2/domains/{domain_name}/mailboxes/{user_name}: Patch Mailbox V2.
func (c *Client) PatchMailboxV2(ctx context.Context, domainName string, userName string, body *UpdateMailbox2) (*Mailbox2, error) {
	return doJSON[Mailbox2](c, ctx, "PATCH", "/v2/domains/"+esc(domainName)+"/mailboxes/"+esc(userName), nil, body)
}

// ChangePassword issues POST /webhook/changepassword: Change Password.
func (c *Client) ChangePassword(ctx context.Context) (string, error) {
	return doValue[string](c, ctx, "POST", "/webhook/changepassword", nil, nil)
}
