// Code generated by internal/gen from openapi.json (Dimail API v0.8.2); DO NOT EDIT.

package dimail

import (
	"context"
	"net/http"
	"net/http/httptest"
	"testing"
)

type smokeServer struct{ body string }

func (s *smokeServer) ServeHTTP(w http.ResponseWriter, r *http.Request) {
	w.Header().Set("Content-Type", "application/json")
	_, _ = w.Write([]byte(s.body))
}

func strPtr(s string) *string { return &s }
func boolPtr(b bool) *bool    { return &b }
func intPtr(i int) *int       { return &i }

// TestGeneratedMethodsSmoke calls every generated method against a mock server,
// covering the single delegating statement (and both query-encoding branches)
// of each. Behavioural assertions live in client_test.go.
func TestGeneratedMethodsSmoke(t *testing.T) {
	srv := &smokeServer{}
	ts := httptest.NewServer(srv)
	defer ts.Close()
	c := NewClient(WithBaseURL(ts.URL), WithToken("t"))
	ctx := context.Background()
	srv.body = `[]`
	_, _ = c.GetPublicAliases(ctx, strPtr("x"))
	srv.body = `[]`
	_, _ = c.GetPublicAliases(ctx, nil)
	srv.body = `{}`
	_, _ = c.PostPublicAlias(ctx, &CreatePubAlias{})
	srv.body = `[]`
	_, _ = c.GetPublicAliasDomains(ctx, strPtr("x"))
	srv.body = `[]`
	_, _ = c.GetPublicAliasDomains(ctx, nil)
	srv.body = `{}`
	_, _ = c.PatchPublicAlias(ctx, "x", "x", "x", &UpdatePubAlias{})
	srv.body = ``
	_ = c.DeletePublicAlias(ctx, "x", "x", "x")
	srv.body = `[]`
	_, _ = c.GetAllow(ctx, strPtr("x"), strPtr("x"))
	srv.body = `[]`
	_, _ = c.GetAllow(ctx, nil, nil)
	srv.body = `{}`
	_, _ = c.PostAllow(ctx, &Allowed{})
	srv.body = ``
	_ = c.DeleteAllow(ctx, "x", "x")
	srv.body = `{}`
	_, _ = c.GetCode(ctx, "x")
	srv.body = `[]`
	_, _ = c.GetDomains(ctx)
	srv.body = `{}`
	_, _ = c.PostDomain(ctx, strPtr("x"), &CreateDomain{})
	srv.body = `{}`
	_, _ = c.PostDomain(ctx, nil, &CreateDomain{})
	srv.body = `{}`
	_, _ = c.GetDomain(ctx, "x")
	srv.body = `{}`
	_, _ = c.PatchDomain(ctx, "x", &UpdateDomain{})
	srv.body = ``
	_ = c.DeleteDomain(ctx, "x")
	srv.body = `{}`
	_, _ = c.GetAddress(ctx, "x", "x")
	srv.body = `[]`
	_, _ = c.GetAlias(ctx, "x", strPtr("x"), strPtr("x"))
	srv.body = `[]`
	_, _ = c.GetAlias(ctx, "x", nil, nil)
	srv.body = `{}`
	_, _ = c.PostAliasDomainsDomainNameAliasesPost(ctx, "x", &CreateAlias{})
	srv.body = `{}`
	_, _ = c.PatchAlias(ctx, "x", "x", "x", &UpdateAlias{})
	srv.body = ``
	_ = c.DeleteAlias(ctx, "x", "x", "x")
	srv.body = `{}`
	_, _ = c.CheckDomain(ctx, "x")
	srv.body = `{}`
	_, _ = c.FixDomain(ctx, "x")
	srv.body = `[]`
	_, _ = c.GetForwards(ctx, "x")
	srv.body = `{}`
	_, _ = c.GetForward(ctx, "x", "x")
	srv.body = `{}`
	_, _ = c.PostForward(ctx, "x", "x", &CreateForward{})
	srv.body = `{}`
	_, _ = c.PatchForward(ctx, "x", "x", &UpdateForward{})
	srv.body = ``
	_ = c.DeleteForward(ctx, "x", "x")
	srv.body = `[]`
	_, _ = c.GetMailboxes(ctx, "x")
	srv.body = `{}`
	_, _ = c.GetMailbox(ctx, "x", "x")
	srv.body = `{}`
	_, _ = c.PostMailbox(ctx, "x", "x", &CreateMailbox{})
	srv.body = `{}`
	_, _ = c.PatchMailbox(ctx, "x", "x", &UpdateMailbox{})
	srv.body = ``
	_ = c.DeleteMailbox(ctx, "x", "x")
	srv.body = `[]`
	_, _ = c.GetAppPasswords(ctx, "x", "x")
	srv.body = `{}`
	_, _ = c.PostAppPassword(ctx, "x", "x", &CreateAppPassword{})
	srv.body = `{}`
	_, _ = c.GetAppPassword(ctx, "x", "x", "x")
	srv.body = ``
	_ = c.DeleteAppPassword(ctx, "x", "x", "x")
	srv.body = `false`
	_, _ = c.CheckPassword(ctx, "x", "x", &MailboxPassword{})
	srv.body = `{}`
	_, _ = c.PostMailboxCode(ctx, "x", "x", &CreateMailboxCode{})
	srv.body = `{}`
	_, _ = c.ForcePassword(ctx, "x", "x", &MailboxForcePassword{})
	srv.body = `[]`
	_, _ = c.GetMailboxIdentities(ctx, "x", "x")
	srv.body = `{}`
	_, _ = c.PostMailboxIdentity(ctx, "x", "x", "x")
	srv.body = `[]`
	_, _ = c.GetMasters(ctx, "x", "x")
	srv.body = `{}`
	_, _ = c.GetMaster(ctx, "x", "x", "x")
	srv.body = `{}`
	_, _ = c.PostMaster(ctx, "x", "x", "x", &CreateSecondary{})
	srv.body = ``
	_ = c.DeleteMaster(ctx, "x", "x", "x")
	srv.body = `[]`
	_, _ = c.GetMastereds(ctx, "x", "x")
	srv.body = `{}`
	_, _ = c.ResetPassword(ctx, "x", "x")
	srv.body = `[]`
	_, _ = c.GetDomainSpecs(ctx, "x")
	srv.body = `[]`
	_, _ = c.GetIdentities(ctx, strPtr("x"))
	srv.body = `[]`
	_, _ = c.GetIdentities(ctx, nil)
	srv.body = `{}`
	_, _ = c.PostIdentity(ctx, &CreateIdentity{})
	srv.body = ``
	_ = c.DeleteIdentities(ctx, "x", "x")
	srv.body = `{}`
	_, _ = c.GetServerLogs(ctx)
	srv.body = `[]`
	_, _ = c.GetCrashLogs(ctx)
	srv.body = `{}`
	_, _ = c.GetCrashLog(ctx, "x")
	srv.body = ``
	_ = c.DeleteCrashLog(ctx, "x")
	srv.body = `[]`
	_, _ = c.GetMyAliases(ctx)
	srv.body = `[]`
	_, _ = c.GetMyDomains(ctx)
	srv.body = `[]`
	_, _ = c.GetMyMailboxes(ctx)
	srv.body = `{}`
	_, _ = c.GetMyResources(ctx)
	srv.body = `{}`
	_, _ = c.UnauthGetDomain(ctx, "x")
	srv.body = `{}`
	_, _ = c.InternalCheckContexts(ctx, &CheckContexts{})
	srv.body = `{}`
	_, _ = c.InternalPatchDatabase(ctx, "x", &UpdateDatabase{})
	srv.body = `{}`
	_, _ = c.InternalPostDatabase(ctx, "x", "x")
	srv.body = `{}`
	_, _ = c.InternalDisconnectUser(ctx, "x", "x")
	srv.body = `{}`
	_, _ = c.HealthCheck(ctx)
	srv.body = `{}`
	_, _ = c.InternalImportDomain(ctx, "x", &ImportDomain{})
	srv.body = `{}`
	_, _ = c.InternalMailboxInfo(ctx, "x", "x")
	srv.body = `[]`
	_, _ = c.InternalMailboxesInfo(ctx, "x")
	srv.body = `[]`
	_, _ = c.InternalGetMailqueue(ctx, "x", "x")
	srv.body = `{}`
	_, _ = c.InternalMoveMailbox(ctx, "x", "x")
	srv.body = `[]`
	_, _ = c.GetRateLimits(ctx)
	srv.body = `{}`
	_, _ = c.GetRateLimit(ctx, "x")
	srv.body = `{}`
	_, _ = c.PostRateLimit(ctx, "x", &RateLimit{})
	srv.body = `{}`
	_, _ = c.PatchRateLimit(ctx, "x", &RateLimit{})
	srv.body = ``
	_ = c.DeleteRateLimit(ctx, "x")
	srv.body = `{}`
	_, _ = c.InternalShutdown(ctx)
	srv.body = `{}`
	_, _ = c.InternalGetStoreInfo(ctx, "x")
	srv.body = `[]`
	_, _ = c.InternalGetStoresInfo(ctx)
	srv.body = `{}`
	_, _ = c.GetTechDomain(ctx)
	srv.body = `{}`
	_, _ = c.GetVersion(ctx)
	srv.body = `{}`
	_, _ = c.GetToken(ctx, strPtr("x"))
	srv.body = `{}`
	_, _ = c.GetToken(ctx, nil)
	srv.body = `[]`
	_, _ = c.GetUsers(ctx)
	srv.body = `{}`
	_, _ = c.PostUser(ctx, &CreateUser{})
	srv.body = `{}`
	_, _ = c.GetUserByProconnectIdentity(ctx, "x")
	srv.body = `{}`
	_, _ = c.GetUser(ctx, "x")
	srv.body = ``
	_ = c.DeleteUser(ctx, "x")
	srv.body = `{}`
	_, _ = c.PatchUser(ctx, "x", &UpdateUser{})
	srv.body = `[]`
	_, _ = c.GetMailboxesV2(ctx, "x", boolPtr(true))
	srv.body = `[]`
	_, _ = c.GetMailboxesV2(ctx, "x", nil)
	srv.body = `{}`
	_, _ = c.GetMailboxV2(ctx, "x", "x", boolPtr(true))
	srv.body = `{}`
	_, _ = c.GetMailboxV2(ctx, "x", "x", nil)
	srv.body = `{}`
	_, _ = c.PostMailboxV2(ctx, "x", "x", &CreateMailbox2{})
	srv.body = `{}`
	_, _ = c.PatchMailboxV2(ctx, "x", "x", &UpdateMailbox2{})
	srv.body = `""`
	_, _ = c.ChangePassword(ctx)
}
