// Code generated by internal/gen from openapi.json (Dimail API v0.8.2); DO NOT EDIT.

package dimail

import "encoding/json"

// Address
type Address struct {
	DomainName     DomainName `json:"domain_name"`
	IsAlias        *bool      `json:"is_alias,omitempty"`
	IsForward      *bool      `json:"is_forward,omitempty"`
	IsMailbox      *bool      `json:"is_mailbox,omitempty"`
	IsOX           *bool      `json:"is_ox,omitempty"`
	OXPrimaryEmail *string    `json:"ox_primary_email,omitempty"`
	OXSenders      []string   `json:"ox_senders,omitempty"`
	UserName       UserName   `json:"user_name"`
}

// AddressName
type AddressName = string

// Alias
type Alias struct {
	AllowToSend *bool  `json:"allow_to_send,omitempty"`
	Destination string `json:"destination"`
	Domain      string `json:"domain"`
	Username    string `json:"username"`
}

// AliasDest
type AliasDest = string

// Allowed allowed model.
type Allowed struct {
	Domain string `json:"domain"`
	User   string `json:"user"`
}

// ApiVersion
type ApiVersion struct {
	Changelog []string `json:"changelog"`
	Version   string   `json:"version"`
}

// AppPassword
type AppPassword struct {
	Client    *string         `json:"client,omitempty"`
	IPAddress *string         `json:"ip_address,omitempty"`
	LastUse   *string         `json:"last_use,omitempty"`
	Login     string          `json:"login"`
	Name      string          `json:"name"`
	Type      AppPasswordType `json:"type"`
	UserAgent *string         `json:"user_agent,omitempty"`
	UUID      string          `json:"uuid"`
}

// AppPasswordType
type AppPasswordType string

const (
	AppPasswordTypeAPI        AppPasswordType = "api"
	AppPasswordTypeIMAP       AppPasswordType = "imap"
	AppPasswordTypeCaldav     AppPasswordType = "caldav"
	AppPasswordTypeCarddav    AppPasswordType = "carddav"
	AppPasswordTypeCalcarddav AppPasswordType = "calcarddav"
)

// Authentication
type Authentication struct {
	Detail string `json:"detail"`
}

// CheckContext
type CheckContext struct {
	Cid        int      `json:"cid"`
	Domains    []string `json:"domains"`
	Name       string   `json:"name"`
	SchemaName string   `json:"schema_name"`
}

// CheckContexts
type CheckContexts struct {
	Contexts []CheckContext `json:"contexts"`
}

// CheckedContext
type CheckedContext struct {
	Cid        int           `json:"cid"`
	Comment    []string      `json:"comment"`
	Domains    []string      `json:"domains"`
	Name       string        `json:"name"`
	SchemaName string        `json:"schema_name"`
	Status     ContextStatus `json:"status"`
}

// CheckedContexts
type CheckedContexts struct {
	Contexts []CheckedContext `json:"contexts"`
	Schemas  map[string]any   `json:"schemas"`
}

// Conflict
type Conflict struct {
	Detail string `json:"detail"`
}

// ContextStatus
type ContextStatus string

const (
	ContextStatusAvailable ContextStatus = "available"
	ContextStatusDiffer    ContextStatus = "differ"
	ContextStatusPartial   ContextStatus = "partial"
	ContextStatusSame      ContextStatus = "same"
)

// CrashInfo
type CrashInfo struct {
	Date string `json:"date"`
	Name string `json:"name"`
	Size int    `json:"size"`
}

// CreateAlias
type CreateAlias struct {
	AllowToSend *bool     `json:"allow_to_send,omitempty"`
	Description *string   `json:"description,omitempty"`
	Destination AliasDest `json:"destination"`
	UserName    UserName  `json:"user_name"`
}

// CreateAppPassword
type CreateAppPassword struct {
	Name string          `json:"name"`
	Type AppPasswordType `json:"type"`
}

// CreateDomain domain creation request model. Quite the same as a Domain, but without the.
type CreateDomain struct {
	ContextID        *int            `json:"context_id,omitempty"`
	ContextName      *string         `json:"context_name,omitempty"`
	Delivery         *Delivery       `json:"delivery,omitempty"`
	Features         []DomainFeature `json:"features"`
	IMAPDomain       *string         `json:"imap_domain,omitempty"`
	MXName           *MXName         `json:"mx_name,omitempty"`
	Name             DomainName      `json:"name"`
	PublicAlias      *bool           `json:"public_alias,omitempty"`
	PublicAliasRules []string        `json:"public_alias_rules,omitempty"`
	SchemaName       *string         `json:"schema_name,omitempty"`
	SMTPDomain       *string         `json:"smtp_domain,omitempty"`
	StoreName        *string         `json:"store_name,omitempty"`
	Transport        *Transport      `json:"transport,omitempty"`
	Webmail          *string         `json:"webmail,omitempty"`
	WebmailDomain    *string         `json:"webmail_domain,omitempty"`
}

// CreateForward
type CreateForward struct {
	Nexthop NextHop `json:"nexthop"`
}

// CreateIdentity
type CreateIdentity struct {
	Email      AddressName `json:"email"`
	Password   string      `json:"password"`
	Proconnect string      `json:"proconnect"`
}

// CreateMailbox request to create a mailbox.
type CreateMailbox struct {
	AdditionalSenders []string `json:"additionalSenders,omitempty"`
	DisplayName       *string  `json:"displayName,omitempty"`
	GivenName         *string  `json:"givenName,omitempty"`
	RateLimit         *string  `json:"rate_limit,omitempty"`
	Store             *string  `json:"store,omitempty"`
	SurName           *string  `json:"surName,omitempty"`
}

// CreateMailbox2
type CreateMailbox2 struct {
	AdditionalSenders []string         `json:"additionalSenders,omitempty"`
	Extras            *MailboxExtra    `json:"extras,omitempty"`
	Features          []MailboxFeature `json:"features"`
	Quota             *QuotaValue      `json:"quota,omitempty"`
	RateLimit         *string          `json:"rate_limit,omitempty"`
	Store             *string          `json:"store,omitempty"`
}

// CreateMailboxCode request to get an access code for a mailbox.
type CreateMailboxCode struct {
	ExpiresIn *int `json:"expires_in,omitempty"`
	Maxuse    *int `json:"maxuse,omitempty"`
}

// CreatePubAlias
type CreatePubAlias struct {
	Description string      `json:"description"`
	Destination AddressName `json:"destination"`
	Domain      DomainName  `json:"domain"`
}

// CreateSecondary
type CreateSecondary struct {
	DisplayName *string `json:"displayName,omitempty"`
}

// CreateUser createUser model.
type CreateUser struct {
	ACLS       []string `json:"acls,omitempty"`
	Identities []string `json:"identities,omitempty"`
	IsAdmin    bool     `json:"is_admin"`
	Name       string   `json:"name"`
	Password   string   `json:"password"`
	Perms      []string `json:"perms"`
}

// Delivery
type Delivery string

const (
	DeliveryVirtual Delivery = "virtual"
	DeliveryAlias   Delivery = "alias"
	DeliveryRelay   Delivery = "relay"
)

// Domain domain model. Contains the results of the sanity checks that may have.
type Domain struct {
	Active           *bool           `json:"active,omitempty"`
	Cert             *TestResult     `json:"cert,omitempty"`
	CnameIMAP        *TestResult     `json:"cname_imap,omitempty"`
	CnameSMTP        *TestResult     `json:"cname_smtp,omitempty"`
	CnameWebmail     *TestResult     `json:"cname_webmail,omitempty"`
	ContextName      *string         `json:"context_name,omitempty"`
	Delivery         json.RawMessage `json:"delivery"`
	DKIM             *TestResult     `json:"dkim,omitempty"`
	DomainExist      *TestResult     `json:"domain_exist,omitempty"`
	Features         []DomainFeature `json:"features"`
	IMAPDomain       *string         `json:"imap_domain,omitempty"`
	MX               *TestResult     `json:"mx,omitempty"`
	MXName           string          `json:"mx_name"`
	Name             string          `json:"name"`
	OX               *TestResult     `json:"ox,omitempty"`
	Postfix          *TestResult     `json:"postfix,omitempty"`
	PublicAlias      *bool           `json:"public_alias,omitempty"`
	PublicAliasRules []string        `json:"public_alias_rules,omitempty"`
	SMTPDomain       *string         `json:"smtp_domain,omitempty"`
	SPF              *TestResult     `json:"spf,omitempty"`
	State            string          `json:"state"`
	StoreName        *string         `json:"store_name,omitempty"`
	Transport        *string         `json:"transport,omitempty"`
	Valid            *bool           `json:"valid,omitempty"`
	Webmail          *string         `json:"webmail,omitempty"`
	WebmailDomain    *string         `json:"webmail_domain,omitempty"`
	WebmailOK        *TestResult     `json:"webmail_ok,omitempty"`
}

// DomainFeature domainFeature enumeration.
type DomainFeature string

const (
	DomainFeatureWebmail DomainFeature = "webmail"
	DomainFeatureMailbox DomainFeature = "mailbox"
	DomainFeatureAlias   DomainFeature = "alias"
	DomainFeatureMX      DomainFeature = "mx"
	DomainFeatureRelay   DomainFeature = "relay"
)

// DomainName
type DomainName = string

// DomainSpec
type DomainSpec struct {
	Target string `json:"target"`
	Type   string `json:"type"`
	Value  string `json:"value"`
}

// FailedMove
type FailedMove struct {
	Detail string `json:"detail"`
}

// Forward
type Forward struct {
	Domain   DomainName `json:"domain"`
	Nexthop  string     `json:"nexthop"`
	Username UserName   `json:"username"`
}

// HTTPValidationError
type HTTPValidationError struct {
	Detail []ValidationError `json:"detail,omitempty"`
}

// ImportDomain
type ImportDomain struct {
	MovingAliases   []MovingAlias   `json:"moving_aliases"`
	MovingDKIM      *MovingDkim     `json:"moving_dkim"`
	MovingFrom      string          `json:"moving_from"`
	MovingMailboxes []MovingMailbox `json:"moving_mailboxes"`
	MovingSenders   []MovingSender  `json:"moving_senders"`
}

// Limit
type Limit struct {
	Emails  int `json:"emails"`
	Seconds int `json:"seconds"`
}

// MXName
type MXName = string

// Mailbox model for a mailbox, as an answer (typicaly to a GET), old version.
type Mailbox struct {
	Active            MailboxActive `json:"active"`
	AdditionalSenders []string      `json:"additionalSenders"`
	DisplayName       *string       `json:"displayName,omitempty"`
	Email             string        `json:"email"`
	GivenName         *string       `json:"givenName,omitempty"`
	RateLimit         *string       `json:"rate_limit,omitempty"`
	Status            MailboxStatus `json:"status"`
	SurName           *string       `json:"surName,omitempty"`
	Type              MailboxType   `json:"type"`
}

// Mailbox2 model for a mailbox, as an answer (typicaly to a GET).
type Mailbox2 struct {
	AdditionalSenders []string         `json:"additionalSenders"`
	DirtyQuirks       map[string]any   `json:"dirty_quirks,omitempty"`
	Email             string           `json:"email"`
	Extras            *MailboxExtra    `json:"extras,omitempty"`
	Features          []MailboxFeature `json:"features,omitempty"`
	IMAPActive        MailboxActive    `json:"imap_active"`
	Quota             *QuotaValue      `json:"quota,omitempty"`
	RateLimit         *string          `json:"rate_limit,omitempty"`
	SMTPActive        MailboxActive    `json:"smtp_active"`
	Type              MailboxType      `json:"type"`
}

// MailboxActive mailbox status.
type MailboxActive string

const (
	MailboxActiveYes     MailboxActive = "yes"
	MailboxActiveNo      MailboxActive = "no"
	MailboxActiveWait    MailboxActive = "wait"
	MailboxActiveUnknown MailboxActive = "unknown"
)

// MailboxCode contains a generated code with its actual parameters.
type MailboxCode struct {
	Code      string `json:"code"`
	Email     string `json:"email"`
	ExpiresAt *int   `json:"expires_at"`
	ExpiresIn *int   `json:"expires_in"`
	Maxuse    *int   `json:"maxuse"`
	Nbuse     int    `json:"nbuse"`
}

// MailboxExtra
type MailboxExtra struct {
	OX       *MailboxExtraOx       `json:"ox,omitempty"`
	Schedule *MailboxExtraSchedule `json:"schedule,omitempty"`
}

// MailboxExtraOx
type MailboxExtraOx struct {
	DisplayName string `json:"display_name"`
	GivenName   string `json:"given_name"`
	SurName     string `json:"sur_name"`
}

// MailboxExtraSchedule
type MailboxExtraSchedule struct {
	Max *int `json:"max,omitempty"`
}

// MailboxFeature
type MailboxFeature string

const (
	MailboxFeatureOX       MailboxFeature = "ox"
	MailboxFeatureSchedule MailboxFeature = "schedule"
)

// MailboxForcePassword contains a (clear text) password for forcing a mailbox's password.
type MailboxForcePassword struct {
	Password        *string `json:"password"`
	RestorePassword *bool   `json:"restore_password,omitempty"`
	SavePassword    *bool   `json:"save_password,omitempty"`
}

// MailboxInfo technical informations about a mailbox, about its storage.
type MailboxInfo struct {
	Email      string          `json:"email"`
	IMAPDir    *bool           `json:"imap_dir,omitempty"`
	MovingAway *bool           `json:"moving_away,omitempty"`
	NeedMoving *bool           `json:"need_moving,omitempty"`
	SieveDir   *bool           `json:"sieve_dir,omitempty"`
	Storage    *MailboxStorage `json:"storage,omitempty"`
	Store      *string         `json:"store,omitempty"`
}

// MailboxPassword contains a password for checking purpose.
type MailboxPassword struct {
	Password string `json:"password"`
}

// MailboxStatus enum class that represents the status of the mailbox.
type MailboxStatus string

const (
	MailboxStatusOK      MailboxStatus = "ok"
	MailboxStatusBroken  MailboxStatus = "broken"
	MailboxStatusUnknown MailboxStatus = "unknown"
)

// MailboxStorage
type MailboxStorage string

const (
	MailboxStorageLocal   MailboxStorage = "local"
	MailboxStorageProxy   MailboxStorage = "proxy"
	MailboxStorageUnknown MailboxStorage = "unknown"
)

// MailboxType enum class that represents the type of the mailbox.
type MailboxType string

const (
	MailboxTypeAlias   MailboxType = "alias"
	MailboxTypeMailbox MailboxType = "mailbox"
)

// ModuleStatus
type ModuleStatus struct {
	Detail []string `json:"detail,omitempty"`
	Status *bool    `json:"status,omitempty"`
}

// Moving
type Moving struct {
	Detail string `json:"detail"`
}

// MovingAlias
type MovingAlias struct {
	Alias       string `json:"alias"`
	Destination string `json:"destination"`
}

// MovingDkim
type MovingDkim struct {
	Private  *string `json:"private"`
	Public   *string `json:"public"`
	Selector *string `json:"selector"`
}

// MovingMailbox
type MovingMailbox struct {
	Active     *string `json:"active,omitempty"`
	IMAPActive *string `json:"imap_active,omitempty"`
	Password   string  `json:"password"`
	RateLimit  *string `json:"rate_limit"`
	SMTPActive *string `json:"smtp_active,omitempty"`
	Username   string  `json:"username"`
}

// MovingSender
type MovingSender struct {
	Login  string `json:"login"`
	Sender string `json:"sender"`
}

// NewAppPassword
type NewAppPassword struct {
	Password string `json:"password"`
	UUID     string `json:"uuid"`
}

// NewMailbox pydantic model that represents a mailbox newly created.
type NewMailbox struct {
	Email    string `json:"email"`
	Password string `json:"password"`
}

// NextHop
type NextHop = string

// NotFound
type NotFound struct {
	Detail string `json:"detail"`
}

// OptionalDomainName
type OptionalDomainName = string

// OptionalMXName
type OptionalMXName = string

// OptionalQuotaValue
type OptionalQuotaValue = string

// OptionalTransport
type OptionalTransport = string

// PermissionDenied
type PermissionDenied struct {
	Detail string `json:"detail"`
}

// PreconditionFailed
type PreconditionFailed struct {
	Detail string `json:"detail"`
}

// PubAlias
type PubAlias struct {
	Alias       string `json:"alias"`
	Description string `json:"description"`
}

// QuotaValue
type QuotaValue = string

// RateLimit
type RateLimit struct {
	Limits []Limit `json:"limits"`
	Name   string  `json:"name"`
}

// SchemaName
type SchemaName struct {
	Name string `json:"name"`
}

// Secondary
type Secondary struct {
	DisplayName *string `json:"displayName,omitempty"`
	DomainName  string  `json:"domain_name"`
	MasterOf    string  `json:"master_of"`
	UserName    string  `json:"user_name"`
}

// ServerLogs
type ServerLogs struct {
	Logs []string `json:"logs"`
}

// ServerStatus
type ServerStatus struct {
	BusinessModule    ModuleStatus `json:"business_module"`
	CertbotModule     ModuleStatus `json:"certbot_module"`
	OpendkimModule    ModuleStatus `json:"opendkim_module"`
	OpenxchangeModule ModuleStatus `json:"openxchange_module"`
	RemoteModule      ModuleStatus `json:"remote_module"`
	SqlAPIModule      ModuleStatus `json:"sql_api_module"`
	SqlDKIMModule     ModuleStatus `json:"sql_dkim_module"`
	SqlIMAPModule     ModuleStatus `json:"sql_imap_module"`
	SqlPostfixModule  ModuleStatus `json:"sql_postfix_module"`
	Status            bool         `json:"status"`
}

// StoreInfo
type StoreInfo struct {
	AvailableInodes *int   `json:"available_inodes,omitempty"`
	AvailableSpace  *int   `json:"available_space,omitempty"`
	Host            string `json:"host"`
	Name            string `json:"name"`
	NbMailboxes     *int   `json:"nb_mailboxes,omitempty"`
	TotalInodes     *int   `json:"total_inodes,omitempty"`
	TotalSpace      *int   `json:"total_space,omitempty"`
	Transport       string `json:"transport"`
	UsedInodes      *int   `json:"used_inodes,omitempty"`
	UsedSpace       *int   `json:"used_space,omitempty"`
}

// TechDomain techDomain model.
type TechDomain struct {
	HostName string `json:"host_name"`
	TechName string `json:"tech_name"`
}

// TestErr
type TestErr struct {
	Code   string `json:"code"`
	Detail string `json:"detail"`
}

// TestResult
type TestResult struct {
	Errors   []TestErr `json:"errors,omitempty"`
	Internal *bool     `json:"internal,omitempty"`
	OK       *bool     `json:"ok,omitempty"`
}

// Token token model.
type Token struct {
	AccessToken string `json:"access_token"`
	TokenType   string `json:"token_type"`
}

// Transport
type Transport = string

// UpdateAlias
type UpdateAlias struct {
	AllowToSend *bool   `json:"allow_to_send,omitempty"`
	Description *string `json:"description,omitempty"`
}

// UpdateDatabase
type UpdateDatabase struct {
	MoveTo string `json:"move_to"`
}

// UpdateDomain
type UpdateDomain struct {
	Active           *bool               `json:"active,omitempty"`
	ContextName      *string             `json:"context_name,omitempty"`
	Delivery         *Delivery           `json:"delivery,omitempty"`
	Features         []string            `json:"features,omitempty"`
	IMAPDomain       *OptionalDomainName `json:"imap_domain,omitempty"`
	MXName           *OptionalMXName     `json:"mx_name,omitempty"`
	PublicAlias      *bool               `json:"public_alias,omitempty"`
	PublicAliasRules []string            `json:"public_alias_rules,omitempty"`
	SchemaName       *string             `json:"schema_name,omitempty"`
	SMTPDomain       *OptionalDomainName `json:"smtp_domain,omitempty"`
	StoreName        *string             `json:"store_name,omitempty"`
	Transport        *OptionalTransport  `json:"transport,omitempty"`
	Webmail          *string             `json:"webmail,omitempty"`
	WebmailDomain    *OptionalDomainName `json:"webmail_domain,omitempty"`
}

// UpdateForward
type UpdateForward struct {
	Nexthop NextHop `json:"nexthop"`
}

// UpdateMailbox
type UpdateMailbox struct {
	Active            *MailboxActive `json:"active,omitempty"`
	AdditionalSenders []string       `json:"additionalSenders,omitempty"`
	DisplayName       *string        `json:"displayName,omitempty"`
	Domain            *DomainName    `json:"domain,omitempty"`
	GivenName         *string        `json:"givenName,omitempty"`
	RateLimit         *string        `json:"rate_limit,omitempty"`
	Store             *string        `json:"store,omitempty"`
	SurName           *string        `json:"surName,omitempty"`
	UserName          *UserName      `json:"user_name,omitempty"`
}

// UpdateMailbox2 updates on a mailbox (v2).
type UpdateMailbox2 struct {
	AdditionalSenders []string            `json:"additionalSenders,omitempty"`
	Domain            *DomainName         `json:"domain,omitempty"`
	Extras            *UpdateMailboxExtra `json:"extras,omitempty"`
	Features          []string            `json:"features,omitempty"`
	IMAPActive        *MailboxActive      `json:"imap_active,omitempty"`
	Quota             *OptionalQuotaValue `json:"quota,omitempty"`
	RateLimit         *string             `json:"rate_limit,omitempty"`
	SMTPActive        *MailboxActive      `json:"smtp_active,omitempty"`
	Store             *string             `json:"store,omitempty"`
	UserName          *UserName           `json:"user_name,omitempty"`
}

// UpdateMailboxExtra
type UpdateMailboxExtra struct {
	OX       *UpdateMailboxExtraOx       `json:"ox,omitempty"`
	Schedule *UpdateMailboxExtraSchedule `json:"schedule,omitempty"`
}

// UpdateMailboxExtraOx
type UpdateMailboxExtraOx struct {
	DisplayName *string `json:"display_name,omitempty"`
	GivenName   *string `json:"given_name,omitempty"`
	SurName     *string `json:"sur_name,omitempty"`
}

// UpdateMailboxExtraSchedule
type UpdateMailboxExtraSchedule struct {
	Max *int `json:"max,omitempty"`
}

// UpdatePubAlias
type UpdatePubAlias struct {
	Description string `json:"description"`
}

// UpdateUser updateUser model.
type UpdateUser struct {
	ACLS       []string `json:"acls,omitempty"`
	Identities []string `json:"identities,omitempty"`
	IsAdmin    *bool    `json:"is_admin,omitempty"`
	Password   *string  `json:"password,omitempty"`
	Perms      []string `json:"perms,omitempty"`
}

// User user model.
type User struct {
	ACLS       []string `json:"acls"`
	Identities []string `json:"identities"`
	IsAdmin    bool     `json:"is_admin"`
	Name       string   `json:"name"`
	Perms      []string `json:"perms"`
	UUID       string   `json:"uuid"`
}

// UserName
type UserName = string

// ValidationError
type ValidationError struct {
	Ctx   map[string]any    `json:"ctx,omitempty"`
	Input json.RawMessage   `json:"input,omitempty"`
	Loc   []json.RawMessage `json:"loc"`
	Msg   string            `json:"msg"`
	Type  string            `json:"type"`
}

// VisibleResources
type VisibleResources struct {
	Aliases   []string `json:"aliases"`
	Domains   []string `json:"domains"`
	Mailboxes []string `json:"mailboxes"`
}
